# Generated by Django 3.2.6 on 2021-08-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='context',
            field=models.TextField(max_length=150, unique=True),
        ),
    ]
